Feature/refectoring
teamtuna/FastCampusTDD pull request #2
Opened 2021-04-12 14:00 UTC by pennya

## 무엇을
- 테스트 코드 리팩토링

## 왜
- 코루틴 delay 관련 코드와 observeForever 코드 삭제하기 위해

## 어떻게
- mock 추가, LiveDataTestUtil 사용

2021-04-13 04:10 UTC, babosamo approved these changes

2021-04-13 05:37 UTC, babosamo approved these changes

2021-04-13 06:05 UTC, eastar-dev requested changes

2021-04-13 06:05 UTC, eastar-dev commented on TDDToySample/app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
```suggestion
```

testImplementation 'org.mockito:mockito-inline:2.21.0'

2021-04-13 06:05 UTC, eastar-dev commented on TDDToySample/app/build.gradle
> +    testImplementation 'org.mockito:mockito-inline:2.21.0'
```suggestion
    testImplementation 'org.mockito:mockito-inline:3.9.0'
```
more new version ??

2021-04-13 06:05 UTC, eastar-dev commented on TDDToySample/app/src/main/java/com/duzi/tddtoysample/ui/single/SingleModeViewModel.kt
>      }
```suggestion
    // 퀴즈 상태
    private val _quizState = Transformations.switchMap(_guess) { guess ->
        _answer.value?.let { answer ->
            MutableLiveData(checkState(answer, guess))
        }
    }
```

2021-04-14 07:45 UTC, pennya commented on TDDToySample/app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
mock-maker-inline 없어도 잘 동작하네요

2021-04-14 07:59 UTC, pennya commented on TDDToySample/app/src/main/java/com/duzi/tddtoysample/ui/single/SingleModeViewModel.kt
>      }
Transformations.switchMap 내부적으로 MediatorLiveData를 사용하고있고
value 에 값 세팅하는 방식보다 더 깔끔한 것 같네요

2021-04-14 09:27 UTC, merged